//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EmployeeContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_EmployeeContact()
        {
            this.HR_tbl_Employee = new HashSet<HR_tbl_Employee>();
        }
    
        public int contactID { get; set; }
        public string Contact { get; set; }
        public int ContactTypeID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
    
        public virtual HR_ContactType HR_ContactType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_tbl_Employee> HR_tbl_Employee { get; set; }
        public virtual HR_tbl_Employee HR_tbl_Employee1 { get; set; }
    }
}
