//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_LeaveType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_LeaveType()
        {
            this.HR_tbl_Emp_Leave = new HashSet<HR_tbl_Emp_Leave>();
            this.HR_tbl_ApprovedLeave = new HashSet<HR_tbl_ApprovedLeave>();
            this.HR_tbl_TakenLeave = new HashSet<HR_tbl_TakenLeave>();
        }
    
        public int LeaveTypeID { get; set; }
        public string LTname { get; set; }
        public Nullable<int> isactive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_tbl_Emp_Leave> HR_tbl_Emp_Leave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_tbl_ApprovedLeave> HR_tbl_ApprovedLeave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_tbl_TakenLeave> HR_tbl_TakenLeave { get; set; }
    }
}
