//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_tbl_Emp_Leave
    {
        public int EMP_ID { get; set; }
        public Nullable<int> EmpStatus_ID { get; set; }
        public Nullable<int> LeavetypeID { get; set; }
        public Nullable<int> Leave_limit { get; set; }
        public Nullable<int> Leave_used { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
        public Nullable<int> isactive { get; set; }
    
        public virtual HR_LeaveType HR_LeaveType { get; set; }
        public virtual HR_tbl_Employee HR_tbl_Employee { get; set; }
    }
}
