//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_tbl_AttendanceLeave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_tbl_AttendanceLeave()
        {
            this.HR_AttendanceRegister = new HashSet<HR_AttendanceRegister>();
        }
    
        public int AttendLeaveID { get; set; }
        public Nullable<int> ApproveLeaveID { get; set; }
        public Nullable<int> TakenLeaveID { get; set; }
    
        public virtual HR_tbl_ApprovedLeave HR_tbl_ApprovedLeave { get; set; }
        public virtual HR_tbl_TakenLeave HR_tbl_TakenLeave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_AttendanceRegister> HR_AttendanceRegister { get; set; }
    }
}
