//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_tbl_SummaryReport
    {
        public int Report_ID { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SL_thismonth { get; set; }
        public Nullable<int> SL_broughtforward { get; set; }
        public Nullable<int> SL_total { get; set; }
        public Nullable<int> CL_thismonth { get; set; }
        public Nullable<int> CL_broughtforward { get; set; }
        public Nullable<int> CL_total { get; set; }
        public Nullable<int> TL_thismonth { get; set; }
        public Nullable<int> TL_broughtforward { get; set; }
        public Nullable<int> TL_total { get; set; }
        public Nullable<int> ML_thismonth { get; set; }
        public Nullable<int> ML_broughtforward { get; set; }
        public Nullable<int> ML_total { get; set; }
        public string remarks { get; set; }
        public Nullable<int> isactive { get; set; }
        public string confirmed { get; set; }
    
        public virtual HR_Department HR_Department { get; set; }
        public virtual HR_tbl_Employee HR_tbl_Employee { get; set; }
    }
}
