//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_tbl_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_tbl_Employee()
        {
            this.HR_tbl_SummaryReport = new HashSet<HR_tbl_SummaryReport>();
            this.HR_tbl_ROP_report = new HashSet<HR_tbl_ROP_report>();
            this.HR_tbl_Employee1 = new HashSet<HR_tbl_Employee>();
            this.HR_EmployeeContact1 = new HashSet<HR_EmployeeContact>();
            this.HR_tbl_Emp_Leave = new HashSet<HR_tbl_Emp_Leave>();
            this.HR_tbl_ApprovedLeave = new HashSet<HR_tbl_ApprovedLeave>();
            this.HR_AttendanceRegister = new HashSet<HR_AttendanceRegister>();
        }
    
        public int EMP_ID { get; set; }
        public string firstName { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> gender { get; set; }
        public string email { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> PosID { get; set; }
        public Nullable<System.DateTime> dateJoin { get; set; }
        public Nullable<System.DateTime> dateLeave { get; set; }
        public Nullable<int> ServiceYears { get; set; }
        public Nullable<int> ReportingManager { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string createdBy { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<int> contactID { get; set; }
    
        public virtual HR_Department HR_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_tbl_SummaryReport> HR_tbl_SummaryReport { get; set; }
        public virtual tbl_val_sex tbl_val_sex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_tbl_ROP_report> HR_tbl_ROP_report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_tbl_Employee> HR_tbl_Employee1 { get; set; }
        public virtual HR_tbl_Employee HR_tbl_Employee2 { get; set; }
        public virtual HR_tbl_employmentStatus HR_tbl_employmentStatus { get; set; }
        public virtual HR_tbl_Location HR_tbl_Location { get; set; }
        public virtual HR_tbl_Position HR_tbl_Position { get; set; }
        public virtual HR_EmployeeContact HR_EmployeeContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_EmployeeContact> HR_EmployeeContact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_tbl_Emp_Leave> HR_tbl_Emp_Leave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_tbl_ApprovedLeave> HR_tbl_ApprovedLeave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_AttendanceRegister> HR_AttendanceRegister { get; set; }
    }
}
