//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRSystemDBEntities : DbContext
    {
        public HRSystemDBEntities()
            : base("name=HRSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HR_Department> HR_Department { get; set; }
        public virtual DbSet<HR_LeaveType> HR_LeaveType { get; set; }
        public virtual DbSet<HR_tbl_Employee> HR_tbl_Employee { get; set; }
        public virtual DbSet<HR_tbl_employmentStatus> HR_tbl_employmentStatus { get; set; }
        public virtual DbSet<HR_tbl_Location> HR_tbl_Location { get; set; }
        public virtual DbSet<HR_tbl_Position> HR_tbl_Position { get; set; }
        public virtual DbSet<HR_tbl_ROP_report> HR_tbl_ROP_report { get; set; }
        public virtual DbSet<HR_tbl_SummaryReport> HR_tbl_SummaryReport { get; set; }
        public virtual DbSet<tbl_val_sex> tbl_val_sex { get; set; }
        public virtual DbSet<HR_ContactType> HR_ContactType { get; set; }
        public virtual DbSet<HR_EmployeeContact> HR_EmployeeContact { get; set; }
        public virtual DbSet<HR_tbl_Emp_Leave> HR_tbl_Emp_Leave { get; set; }
        public virtual DbSet<HR_tbl_ApprovedLeave> HR_tbl_ApprovedLeave { get; set; }
        public virtual DbSet<HR_AttendanceRegister> HR_AttendanceRegister { get; set; }
        public virtual DbSet<HR_tbl_TakenLeave> HR_tbl_TakenLeave { get; set; }
    
        public virtual int spGetDeptAttendance(Nullable<int> deptID)
        {
            var deptIDParameter = deptID.HasValue ?
                new ObjectParameter("deptID", deptID) :
                new ObjectParameter("deptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetDeptAttendance", deptIDParameter);
        }
    
        public virtual int spGetDeptAttendance1(Nullable<int> deptID)
        {
            var deptIDParameter = deptID.HasValue ?
                new ObjectParameter("deptID", deptID) :
                new ObjectParameter("deptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetDeptAttendance1", deptIDParameter);
        }
    
        public virtual int spGetDeptAttendance2(Nullable<int> deptID)
        {
            var deptIDParameter = deptID.HasValue ?
                new ObjectParameter("deptID", deptID) :
                new ObjectParameter("deptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetDeptAttendance2", deptIDParameter);
        }
    
        public virtual int spGetDeptAttendance3(Nullable<int> deptID)
        {
            var deptIDParameter = deptID.HasValue ?
                new ObjectParameter("deptID", deptID) :
                new ObjectParameter("deptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetDeptAttendance3", deptIDParameter);
        }
    
        public virtual int spGetDeptAttendance4(Nullable<int> deptID)
        {
            var deptIDParameter = deptID.HasValue ?
                new ObjectParameter("deptID", deptID) :
                new ObjectParameter("deptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetDeptAttendance4", deptIDParameter);
        }
    
        public virtual ObjectResult<spGetDeptAttendance5_Result> spGetDeptAttendance5(Nullable<int> deptID)
        {
            var deptIDParameter = deptID.HasValue ?
                new ObjectParameter("deptID", deptID) :
                new ObjectParameter("deptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDeptAttendance5_Result>("spGetDeptAttendance5", deptIDParameter);
        }
    }
}
